version: "3.9"

services:
  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    restart: on-failure:1
    container_name: db-service
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - configs/service.env
    networks:
      - db-network

  postgres:
    image: postgres:17
    container_name: db-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-postgres-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready", "-d", "postgres"]
        interval: 10s
        timeout: 3s
        retries: 3
    restart: on-failure:3
    networks:
      - db-network

networks:
  db-network:

volumes:
  db-postgres-data:
    name: db-postgres-data
